export const darkTheme = {
	name: "dark",
	colors: {
		backgroundPage: "#161616",
		backgroundPageRgb: [22, 22, 22],
		backgroundGradient: "linear-gradient(to left top, #252525, #0C0C0C)",
		backgroundRadial: "radial-gradient(ellipse at center, #2e2e2e, #0C0C0C)",
		background: "#000",
		backgroundSecondary: "#272727",
		backgroundTertiary: "#313131",
		branding: "#fec800",
		brandingDarker: "#c79d07",
		title: "#fff",
		inactiveTitle: "#8b8b8b",
		subtitle: "#b1b1b1",
		body: "#ccc",
		contrastText: "#2b2b2b",
		caption: "#ccc",
		icon: "#fff",
		iconHover: "#9b883c",
		button: "",
		shadow: "",
	},
	fontSizes: {
		xs: "12px",
		sm: "14px",
		md: "16px",
		lg: "18px",
		xl: "20px",
	},
};

export const lightTheme = {
    name: "light",
    colors: {
        backgroundPage: "#ffffff",
        backgroundPageRgb: [255, 255, 255],
        backgroundGradient: "linear-gradient(180deg, #ffffff 0%, #ffffff 100%)",
        backgroundRadial: "radial-gradient(circle, #ffffff 0%, #ffffff 100%)",
        background: "#ffffff",
        backgroundSecondary: "#f6f6f9",
        backgroundTertiary: "#f6f6f9",
        branding: "#7c5cff",
        brandingDarker: "#5a3efc",
        title: "#0f0f0f",
        inactiveTitle: "#a1a1aa",
        subtitle: "#6b7280",
        body: "#3f3f46",
        contrastText: "#2b2b2b",
        caption: "#ccc",
        icon: "#fff",
        iconHover: "#000000",
        button: "",
        shadow: "",
    },
    fontSizes: {
        xs: "12px",
        sm: "14px",
        md: "16px",
        lg: "18px",
        xl: "20px",
    },
};
